### ISSUE TITLE
No project License

### ISSUE THREAD

**Issue by alaxalves** [looqbox/statuspageio#3]
## What did you get
No `LICENSE` file on repository.

## What was expected
Should have a license.

## System Settings
Linux Mint 19

```
go_version: go1.14.3 linux/amd64
```

**Comment by alaxalves** [comment]
@nivaldogmelo WhichdDo you think that would apply to this?

**Creative Commons Attribution-NonCommercial-NoDerivs (CC-BY-NC-ND):** The most restrictive creative commons license. This only allows people to download and share your work for no commercial gain and for no other purposes.

**Creative Commons Attribution-NonCommercial-ShareAlike (CC-BY-NC-SA):** A creative commons license that bans commercial use and requires you to release any modified works under this license.

**Comment by dmurta1** [comment]
Let's start this project with CC BY-NC-SA
